/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 967728cb19cce4a15a5b850b0670900d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "CoordinatorAgent" | "GalleryAgent";
	}
	interface Env {
		OPENAI_API_KEY: string;
		CoordinatorAgent: DurableObjectNamespace<import("./src/server").CoordinatorAgent>;
		GalleryAgent: DurableObjectNamespace<import("./src/server").GalleryAgent>;
		AI: Ai;
		SCRAPE_WORKFLOW: Workflow<Parameters<import("./src/server").ScrapeWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> { }
}
